### ISSUE TITLE
Clang 16 compilation error: __malloc__' attribute takes no arguments _GL_ATTRIBUTE_MALLOC _GL_ATTRIBUTE_DEALLOC_FREE)

### ISSUE THREAD

**Issue by AngryPenguinPL** [rrthomas/enchant#327]
Hi.

Trying compile enchant 2.5.0 on OpenMandriva Cooker with Clang 16 and see this build error. Worth to add package compile fine with GCC 13.1.

```
DEBUG util.py:445:  make[2]: Entering directory '/builddir/build/BUILD/enchant-2.5.0/src'
DEBUG util.py:445:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I..  -I.. -isystem ../lib -isystem ../lib -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fno-common -Wall -Wbad-function-cast -Wdate-time -Wdisabled-optimization -Wdouble-promotion -Wextra -Winit-self -Winline -Winvalid-pch -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wnull-dereference -Wold-style-definition -Woverlength-strings -Wpacked -Wpointer-arith -Wshadow -Wstack-protector -Wstrict-overflow -Wstrict-prototypes -Wuninitialized -Wunknown-pragmas -Wvariadic-macros -Wvla -Wwrite-strings -Wformat=2   -Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -flto -c -o enchant-lsmod.o enchant-lsmod.c
DEBUG util.py:445:  make[2]: Leaving directory '/builddir/build/BUILD/enchant-2.5.0/src'
DEBUG util.py:443:  In file included from enchant-lsmod.c:33:
DEBUG util.py:443:  In file included from /usr/include/glib-2.0/glib.h:32:
DEBUG util.py:443:  In file included from /usr/include/glib-2.0/glib/galloca.h:35:
DEBUG util.py:443:  ../lib/string.h:1033:40: error: '__malloc__' attribute takes no arguments
DEBUG util.py:443:                    _GL_ATTRIBUTE_MALLOC _GL_ATTRIBUTE_DEALLOC_FREE);
DEBUG util.py:443:                                         ^
DEBUG util.py:443:  ../config.h:626:37: note: expanded from macro '_GL_ATTRIBUTE_DEALLOC_FREE'
DEBUG util.py:443:  # define _GL_ATTRIBUTE_DEALLOC_FREE _GL_ATTRIBUTE_DEALLOC (free, 1)
DEBUG util.py:443:                                      ^
DEBUG util.py:443:  ../config.h:618:54: note: expanded from macro '_GL_ATTRIBUTE_DEALLOC'
DEBUG util.py:443:  # define _GL_ATTRIBUTE_DEALLOC(f, i) __attribute__ ((__malloc__ (f, i)))
DEBUG util.py:443:                                                       ^
DEBUG util.py:443:  In file included from enchant-lsmod.c:33:
DEBUG util.py:443:  In file included from /usr/include/glib-2.0/glib.h:32:
DEBUG util.py:443:  In file included from /usr/include/glib-2.0/glib/galloca.h:35:
DEBUG util.py:443:  ../lib/string.h:1116:40: error: '__malloc__' attribute takes no arguments
DEBUG util.py:443:                    _GL_ATTRIBUTE_MALLOC _GL_ATTRIBUTE_DEALLOC_FREE);
DEBUG util.py:443:                                         ^
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/28235d9694b98096158e0239f6b95bb8d9af86d6.log?show=true

**Comment by rrthomas** [comment]
Thanks, that looks like a gnulib bug, I'll check it out.

**Comment by rrthomas** [comment]
I had a look, and I don't understand why Clang is getting the wrong definition of `_GL_ATTRIBUTE_DEALLOC`.

The definition in `config.h` is:

```
#if _GL_GNUC_PREREQ (11, 0)
# define _GL_ATTRIBUTE_DEALLOC(f, i) __attribute__ ((__malloc__ (f, i)))
#else
# define _GL_ATTRIBUTE_DEALLOC(f, i)
#endif
```

and the definition of `_GL_GNUC_PREREQ` is:

```
#if defined __GNUC__ && defined __GNUC_MINOR__
# define _GL_GNUC_PREREQ(major, minor) \
    ((major) < __GNUC__ + ((minor) <= __GNUC_MINOR__))
#else
# define _GL_GNUC_PREREQ(major, minor) 0
#endif
```

and `clang-16` tells me that `__GNUC__` is `4`.

Indeed, when I build with clang 16.0.4, I have no problem.

**Comment by AngryPenguinPL** [comment]
Thanks, it seems the problem was in the modified clang compiler on the openmandriva side.
We have applied this patch to avoid the problem.
https://github.com/OpenMandrivaAssociation/enchant2/commit/f7e91d1bb0983f9c874384ebf55fc93adfbeb2d8
Sorry for the confusion.
